let words = [
[1, 'query', 'запрос'],
[2, 'while', 'пока'],
[3, 'statement', 'отчет'],
[4, 'fetch', 'извлечь'],
[5, 'relation', 'связь'],
[6, 'position relative', 'положение относительно'],
[7, 'bottom', 'дно'],
[8, 'padding', 'набивка'],
[9, 'view', 'вид'],
[10, 'cell', 'ячейка'],
[11, 'miss', 'промах'],
[12, 'comparsion', 'сравнение'],
[13, 'entry', 'вход'],
[14, 'confirm', 'подтверждаю'],
[15, 'inherit', 'наследовать'],
[16, 'float', 'плыть'],
[17, 'keep', 'держать'],
[18, 'always', 'всегда'],
[19, 'event', 'событие'],
[20, 'ever', 'когда-либо'],
[21, 'width', 'ширина'],
[22, 'height', 'высота'],
[23, 'weight', 'вес'],
[24, 'opacity', 'непрозрачность'],
[25, 'hopelessness', 'безисходность'],
[26, 'gender', 'пол'],
[27, 'responded', 'ответил'],
[28, 'few', 'несколько'],
[29, 'too', 'тоже'],
[30, 'too few', 'слишком мало'],
[31, 'uncaught', 'не пойманный'],
[32, 'sign', 'знак'],
[33, 'board', 'доска'],
[34, 'dashboard', 'приборная панель'],
[35, 'even', 'даже'],
[36, 'extends', 'расширяться'],
[37, 'viewport', 'окно просмотра'],
[38, 'response', 'ответ'],
[39, 'send', 'отправлять'],
[40, 'required', 'требуемый'],
[41, 'remote', 'удаленный'],
[42, 'trim', 'обрезать'],
[43, 'uncle', 'дядя'],
[44, 'nose', 'нос'],
[45, 'template', 'шаблон'],
[46, 'access', 'доступ'],
[47, 'denied', 'отказано'],
[48, 'appear', 'появляться'],
[49, 'throw', 'бросать'],
[50, 'right', 'правильно'],
[51, 'wrong', 'неправильно'],
[52, 'include', 'включать в себя'],
[53, 'require', 'требовать'],
[54, 'space', 'пространство'],
[55, 'development', 'разработка'],
[56, 'immediate', 'немедленный'],
[57, 'availability', 'доступность'],
[58, 'release', 'выпуск'],
[59, 'encouraged', 'рекомендуется'],
[60, 'our', 'наш'],
[61, 'binaries', 'двоичные файлы'],
[62, 'try', 'пытаться'],
[63, 'catch', 'ловить'],
[64, 'self', 'сам'],
[65, 'guide', 'руководство'],
[66, 'through', 'через'],
[67, 'vendor', 'разработчик'],
[68, 'description', 'описание'],
[69, 'skip', 'пропускать'],
[70, 'define', 'определять'],
[71, 'dependencies', 'зависимости'],
[72, 'search', 'поиск'],
[73, 'package', 'пакет'],
[74, 'dependencies', 'зависимости'],
[75, 'interactively', 'интерактивно'],
[76, 'enterprise', 'предприятие'],
[77, 'such', 'такой'],
[78, 'prepare', 'подготавливать'],
[79, 'execute', 'выполнять'],
[80, 'available', 'доступный'],
[81, 'fix', 'исправлять'],
[82, 'source', 'источник'],
[83, 'pick', 'выбирать'],
[84, 'below', 'ниже'],
[85, 'note', 'обратите внимание'],
[86, 'under', 'под'],
[87, 'just', 'просто'],
[88, 'still', 'все еще'],
[89, 'might', 'вероятно'],
[90, 'outdated', 'устаревший'],
[91, 'contribution', 'взнос'],
[92, 'involved', 'вовлеченный'],
[93, 'anybody', 'любой'],
[94, 'deploys', 'развертывает'],
[95, 'never ending one', 'бесконечный список'],
[96, 'wave', 'волна'],
[97, 'lot', 'много'],
[98, 'introduction', 'внедрение'],
[99, 'smoother', 'плавно'],
[100, 'squashing', 'сжатие'],
[101, 'hide', 'прятать'],
[102, 'specified', 'указанный'],
[103, 'piece', 'кусок'],
[104, 'expires', 'истекает'],
[105, 'delay', 'задержка'],
[106, 'span', 'промежуток'],
[107, 'floor', 'этаж'],
[108, 'common', 'общий'],
[109, 'rise', 'подъем'],
[110, 'compound', 'соединение'],
[111, 'learn', 'учиться'],
[112, 'build', 'строить'],
[113, 'tutorials', 'учебные пособия'],
[114, 'earn', 'зарабатывать'],
[115, 'apply', 'применять'],
[116, 'extensions', 'расширения'],
[117, 'interfer', 'вмешиваться'],
[118, 'expressions', 'выражения'],
[119, 'very often', 'очень часто'],
[120, 'pattern', 'шаблон'],
[121, 'approach', 'подход'],
[122, 'expand', 'расширять'],
[123, 'count', 'считать'],
[124, 'until', 'до тех пор'],
[125, 'point', 'точка'],
[126, 'until this point', 'до этого момента'],
[127, 'solve', 'решать'],
[128, 'entire', 'весь'],
[129, 'whole', 'весь'],
[130, 'larger whole', 'большое целое'],
[131, 'margin', 'поле'],
[132, 'alter', 'изменять'],
[133, 'each', 'каждый'],
[134, 'preface', 'предисловие'],
[135, 'widely-used', 'широко используемый'],
[136, 'general-purpose', 'общего назначения'],
[137, 'especially', 'особенно'],
[138, 'suited', 'подходящий'],
[139, 'embedded', 'встроенный'],
[140, 'draws upon C', 'опирается на с'],
[141, 'goal', 'цель'],
[142, 'allow', 'позволять'],
[143, 'consists primarily', 'состоит в первую очередь'],
[144, 'reference', 'ссылка'],
[145, 'contains', 'содержит'],
[146, 'explanations', 'объяснения'],
[147, 'major', 'главный'],
[148, 'minor', 'незначительный'],
[149, 'features', 'особенности'],
[150, 'supplemental information', 'дополнительная информация'],
[151, 'violation', 'нарушение'],
[152, 'rule', 'правило'],
[153, 'alumni', 'выпускники'],
[154, 'scary to change careers', 'страшно менять карьеру'],
[155, 'gained confidence', 'обрел уверенность'],
[156, 'within a year', 'в течение года'],
[157, 'software engineer', 'инженер-программист'],
[158, 'six-figure job', 'работа с шестизначной суммой'],
[159, 'well', 'хорошо'],
[160, 'curriculum', 'учебный план'],
[161, 'beginner', 'начинающий'],
[162, 'condident', 'уверенный'],
[163, 'amazing', 'удивительный'],
[164, 'struggle', 'борьба'],
[165, 'stuck', 'застрял'],
[166, 'studying', 'изучение'],
[167, 'skills', 'навыки'],
[168, 'confidence', 'уверенность'],
[169, 'responsive', 'отзывчивый'],
[170, 'share', 'делиться'],
[171, 'human rights violation', 'нарушение прав человека'],
[172, 'black is not sad', 'черный - это не грустно'],
[173, 'internal', 'внутренний'],
[174, 'parse', 'разбор'],
[175, 'between', 'между'],
[176, 'manner', 'манера'],
[177, 'everything', 'все'],
[178, 'pair', 'пара'],
[179, 'verbose', 'подробный'],
[180, 'three', 'три'],
[181, 'either', 'любой'],
[182, 'either via', 'с помощью'],
[183, 'via', 'посредством'],
[184, 'compatibility', 'совместимость'],
[185, 'as', 'как'],
[186, 'prefarable', 'предпочтительный'],
[187, 'omit', 'пропускать'],
[188, 'prevents', 'предотвращает'],
[189, 'accidental', 'случайный'],
[190, 'whitespace', 'пробел'],
[191, 'forbidden', 'запрещенный'],
[192, 'exists', 'существует'],
[193, 'discover', 'обнаруживать'],
[194, 'forgot', 'забыл'],
[195, 'explore', 'исследовать'],
[196, 'following', 'следующий'],
[197, 'to populate', 'для заполнения'],
[198, 'feed', 'кормить'],
[199, 'news feed', 'лента новостей'],
[200, 'keep up', 'следить'],
[201, 'recent activity', 'недавняя активность'],
[202, 'watch', 'часы'],
[203, 'watch tv', 'смотреть телевизор'],
[204, 'memorable', 'запоминающийся'],
[205, 'need inspiration?', 'нужно вдохновение?'],
[206, 'existing', 'существующий'],
[207, 'commit', 'совершать'],
[208, 'push', 'толкать'],
[209, 'does not appear', 'не является'],
[210, 'branch', 'ветка'],
[211, 'able', 'способный'],
[212, 'authentication succceeded', 'аутентификация прошла успешно'],
[213, 'issues', 'вопросы'],
[214, 'offers', 'предложения'],
[215, 'namely', 'именно'],
[216, 'opening brace', 'открывающая скобка'],
[217, 'should', 'должен'],
[218, 'feed the cat', 'кормить кота'],
[219, 'that allow you', 'которые позволяют вам'],
[220, 'he liked to apply', 'ему нравилось использовать'],
[221, 'the cat is not able to fly', 'кот не способен летать'],
[222, 'every time the same', 'каждый раз одно и то же'],
[223, 'apply in practice', 'применять на практике'],
[224, 'views', 'просмотры'],
[225, 'view', 'вид'],
[226, 'empty spaces', 'пустые места'],
[227, 'what a we living for', 'для чего мы живем'],
[228, 'abandoned places', 'заброшенные места'],
[229, 'i guess we know the score', 'я думаю мы знаем счет'],
[230, 'on and on', 'продолжается и продолжается'],
[231, 'does anybody know?', 'кто-нибудь знает?'],
[232, 'what we are looking for?', 'что мы ищем?'],
[233, 'another hero', 'еще один герой'],
[234, 'another mindless crime', 'еще одно бессмысленное преступление'],
[235, 'behind the curtain', 'за занавеской'],
[236, 'in the pantomime', 'в пантомиме'],
[237, 'hold the line', 'держи оборону'],
[238, 'does anybody want', 'кто-нибудь хочет'],
[239, 'to take it anymore?', 'терпеть это больше?'],
[240, 'show must go on', 'шоу должно продолжаться'],
[241, 'inside my heart is breaking', 'внутри мое сердце разрывается'],
[242, 'must have', 'необходимый'],
[243, 'my makeup may be flaking', 'мой макияж может быть и отслаивается'],
[244, 'but my smile, still, stays on', 'но моя улыбка все еще остается на мне'],
[245, 'whatever happens', 'что бы ни случилось'],
[246, 'i\'ll leave it all to chance', 'я оставлю все на волю случая'],
[247, 'another heartache', 'еще одна боль в сердце'],
[248, 'another failed romance', 'еще один неудавшийся роман'],
[249, 'does anybody know?', 'кто-нибудь знает?'],
[250, 'what we are living for?', 'для чего мы живем?'],
[251, 'layout', 'расположение'],
[252, 'supported content', 'поддерживаемый контент'],
[253, 'overview', 'обзор'],
[254, 'blast', 'взрыв'],
[255, 'blast from the past', 'привет из прошлого'],
[256, 'confirmation', 'подтверждение'],
[257, 'assets', 'активы'],
[258, 'i guess i\'m learning', 'я думаю я учусь'],
[259, 'i must be warmer now', 'я должен быть теплее сейчас'],
[260, 'i\'ll soon be turning', 'я скоро превращусь'],
[261, 'around the corner now', 'за угол теперь'],
[262, 'outside the dawn is breaking', 'снаружи светает'],
[263, 'but inside in the dark', 'но внутри в темноте'],
[264, 'im aching to be free', 'я жажду быть свободным'],
[265, 'my soul is painted', 'моя душа разрисована'],
[266, 'like the wings of butterflies', 'как крылья бабочек'],
[267, 'fairy tales of yesterdays', 'сказки вчерашних дней'],
[268, 'ill face it with a grin', 'я встречу это с усмешкой'],
[269, 'ill never giving in', 'я никогда не сдамся'],
[270, 'on whith the show', 'продолжайте шоу'],
[271, 'top the bill', 'возглавить список'],
[272, 'overkill', 'перебор'],
[273, 'i have to find the will to carry on', 'я должен найти в себе волю продолжать'],
[274, 'shedding skin', 'сбрасывающая кожу'],
[275, 'with anyone else', 'с кем-нибудь еще'],
[276, 'check me out', 'проверить меня'],
[277, 'lie', 'ложь'],
[278, 'false', 'ложный'],
[279, 'true', 'истинный'],
[280, 'password confirmation', 'подтверждение пароля'],
[281, 'placeholder', 'заполнитель'],
[282, 'environment', 'окружающая среда'],
[283, 'report any issues', 'сообщайте о любых проблемах'],
[284, 'some required updates', 'некоторые необходимые обновления'],
[285, 'fix issue', 'исправлена проблема'],
[286, 'feature discussion', 'обсуждение особенностей'],
[287, 'semicolon', 'точка с запятой'],
[288, 'removed extra spaces', 'удалены лишние пробелы'],
[289, 'snippet output', 'вывод фрагмента кода'],
[290, 'there\'s something cold and blank', 'есть что-то холодное и пустое'],
[291, 'behind her smile', 'за ее улыбкой'],
[292, 'she\'s standing on an overpass', 'она стоит на эстакаде'],
[293, 'drug the water some more', 'добавь в воду еще немного наркотика'],
[294, 'drug', 'медикамент'],
[295, 'in her miracle mile', 'в ее чудодейственной миле'],
[296, 'untracked', 'неотслеживаемый'],
[297, 'request', 'запрос'],
[298, 'sniffer', 'нюхач'],
[299, 'soon', 'скоро'],
[300, 'happen', 'случаться'],
[301, 'toggle', 'тумблер'],
[302, 'length', 'длина'],
[303, 'case you were from a perfect world', 'на случай, если вы были из идеального мира'],
[304, 'a world that threw me away, today', 'мир, который отбросил меня сегодня'],
[305, 'today, to run away', 'сегодня, чтобы убежать'],
[306, 'went', 'пошел'],
[307, 'improve', 'улучшать'],
[308, 'performance', 'представление'],
[309, 'improve performance', 'повысить производительность'],
[310, 'an', 'один'],
[311, 'educator', 'преподаватель'],
[312, 'join', 'присоединяться'],
[313, 'snag the spotlight', 'привлеките внимание'],
[314, 'just hover', 'просто наведите курсор'],
[315, 'lead your teammaters', 'веди своих товарищей по команде'],
[316, 'travel', 'путешествовать'],
[317, 'follow', 'следовать'],
[318, 'favicon', 'значок сайта'],
[319, 'item', 'элемент'],
[320, 'befor', 'перед'],
[321, 'after', 'после'],
[322, 'shape', 'форма'],
[323, 'preview', 'предварительный просмотр'],
[324, 'wrapper', 'обертка'],
[325, 'remove from recent', 'удалить из недавних'],
[326, 'intro', 'вступление'],
[327, 'cover', 'покрытие'],
[328, 'justify-content', 'обосновать содержание'],
[329, 'space-between', 'пространство между'],
[330, 'balcony', 'балкон'],
[331, 'onto', 'на'],
[332, 'stranger', 'незнакомец'],
[333, 'jump of balcony, onto stranger\'s head', 'спрыгните с балкона на голову незнакомца'],
[334, 'chase', 'преследовать'],
[335, 'chase ball of string', 'гоняться за клубком ниток'],
[336, 'guests come over', 'гости приходят'],
[337, 'rush', 'спешка'],
[338, 'being', 'существование'],
[339, 'gorgeous', 'великолепный'],
[340, 'being gorgeous', 'быть великолепной'],
[341, 'search', 'поиск'],
[342, 'flex-wrap', 'гибкая обертка'],
[343, 'wrap', 'заворачивать'],
[344, 'bring', 'приносить'],
[345, 'brain', 'мозг'],
[346, 'abound', 'изобиловать'],
[347, 'trap', 'ловушка'],
[348, 'hike', 'поход'],
[349, 'chat', 'болтать'],
[350, 'chatty', 'болтливый'],
[351, 'laugh', 'смеяться'],
[352, 'grid', 'сетка'],
[353, 'cross axis', 'поперечная ось'],
[354, 'columns', 'столбцы'],
[355, 'rows', 'строки'],
[356, 'chapters', 'главы'],
[357, 'parent', 'родитель'],
[358, 'building', 'здание'],
[359, 'fill', 'заполнять'],
[360, 'shape', 'форма'],
[361, 'inspired', 'вдохновленный'],
[362, 'caption', 'подпись'],
[363, 'scale', 'масштаб'],
[364, 'gap', 'пробел'],
[365, 'fraction', 'фракция'],
[366, 'consider', 'рассматривать'],
[367, 'sure', 'конечно'],
[368, 'make sure', 'убедиться'],
[369, 'accessibility', 'доступность'],
[370, 'excess carbon dioxide', 'избыток двуокиси углерода'],
[371, 'known issue', 'известная проблема'],
[372, 'oddly', 'странно'],
[373, 'unit', 'единица измерения'],
[374, 'adjust', 'регулировать'],
[375, 'without', 'без'],
[376, 'will', 'будет'],
[377, 'carry on', 'продолжать'],
[378, 'carry', 'нести'],
[379, 'tales', 'сказки'],
[380, 'two', 'два'],
[381, 'impossible', 'невозможно'],
[382, 'everyone', 'каждый'],
[383, 'prevents', 'предотвращает'],
[384, 'drag and drop', 'перетаскивание'],
[385, 'display', 'отображение'],
[386, 'infinite', 'бесконечный'],
[387, 'transition', 'переход'],
[388, 'transform', 'преобразовать'],
[389, 'scale', 'масштаб'],
[390, 'transform scale', 'масштаб преобразования'],
[391, 'overflow', 'переполнение'],
[392, 'handle', 'справляться'],
[393, 'so', 'так'],
[394, 'hidden', 'скрытый'],
[395, 'choose', 'выбирать'],
[396, 'preferences', 'предпочтения'],
[397, 'current', 'текущий'],
[398, 'scheme', 'схема'],
[399, 'trial', 'пробный'],
[400, 'snippets', 'фрагменты'],
[401, 'external', 'внешний'],
[402, 'lazy', 'ленивый'],
[403, 'solution', 'решение'],
[404, 'former', 'бывший'],
[405, 'hush', 'тишина'],
[406, 'payment', 'оплата'],
[407, 'expect', 'ожидать'],
[408, 'supposedly imminent arrest', 'предположительно неизбежный арест'],
[409, 'transparent', 'прозрачный'],
[410, 'aim', 'цель'],
[411, 'assess', 'оценивать'],
[412, 'provided', 'представленный'],
[413, 'separate out', 'отделять'],
[414, 'field', 'поле'],
[415, 'distinct containers', 'отдельные контейнеры'],
[416, ' descriptive', 'описательный'],
[417, 'appropriate element', 'соответствующий элемент'],
[418, 'semantically associated', 'семантически связанный'],
[419, 'respective form field', 'соответствующее поле формы'],
[420, 'above', 'выше'],
[421, 'suggestion', 'предложения'],
[422, 'solid black', 'сплошной черный'],
[423, 'most recent', 'самый последний'],
[424, 'derivative', 'производное'],
[425, 'law', 'закон'],
[426, 'option unset', 'опция не установлена'],
[427, 'this will leave', 'это оставит'],
[428, 'leave', 'покидать'],
[429, 'decide', 'решать'],
[430, 'deicide', 'богоубийство'],
[431, 'affect', 'влиять'],
[432, 'most', 'наибольший'],
[433, 'most cautious choice', 'наиболее осторожный выбор'],
[434, 'at all', 'вообще'],
[435, 'tools', 'инструменты'],
[436, 'optional', 'необязательный'],
[437, 'clutter', 'беспорядок'],
[438, 'cluttering', 'загромождающий'],
[439, 'fit', 'подходить'],
[440, 'object fit', 'объект вписывается'],
[441, 'launch', 'запуск'],
[442, 'current', 'текущий'],
[443, 'evenly', 'равномерно'],
[444, 'set', 'устанавливать'],
[445, 'let', 'позволять'],
[446, 'cover', 'покрытие'],
[447, 'as far as', 'поскольку'],
[448, 'far', 'далеко'],
[449, 'sub-object', 'подобъект'],
[450, 'then', 'тогда'],
[451, 'answer', 'ответ'],
[452, 'advisory', 'консультативный'],
[453, 'accordingly', 'соответственно'],
[454, 'could be used', 'мог бы быть использован'],
[455, 'seems like', 'кажется, что'],
[456, 'considered', 'рассмотрен'],
[457, 'involving', 'включающий'],
[458, 'unless the Text is a sub-object of the Image', 'если только текст не является подобъектом изображения'],
[459, 'mean', 'означать'],
[460, 'do you mean you want to change the size', 'вы имеете в виду, что хотите изменить размер'],
[461, 'same', 'такой же'],
[462, 'probably', 'возможно'],
[463, 'hierarchy', 'иерархия'],
[464, 'has', 'имеет'],
[465, 'has to be', 'должен быть'],
[466, 'simply', 'просто'],
[467, 'treated', 'обработанный'],
[468, 'be', 'быть'],
[469, 'been', 'бывший'],
[470, 'as usual', 'как обычно'],
[471, 'i missed you', 'я скучал по тебе'],
[472, 'occasion', 'случай'],
[473, 'special occasion', 'особый случай'],
[474, 'pot roast', 'тушеное мясо'],
[475, 'sweet', 'сладкий'],
[476, 'feet', 'ноги'],
[477, 'duration', 'продолжительность'],
[478, 'i\'m proud of you', 'я горжусь тобой'],
[489, 'embarrassed', 'смущенный'],
[480, 'clown', 'клоун'],
[481, 'leave no trace', 'не оставляй следов'],
[482, 'canvas', 'холст'],
[483, 'sick of it all', 'надоело все это'],
[484, 'inspire confidence', 'внушать доверие'],
[485, 'inspire', 'внушать'],
[486, 'rect', 'прямоугольник'],
[487, 'i believe you', 'я верю тебе'],
[488, 'impact of the crisis', 'влияние кризиса'],
[489, 'opportunity', 'возможность'],
[490, 'else', 'еще'],
[491, 'does she expect you?', 'она тебя ждет?'],
[492, 'sad occasion', 'печальный случай'],
[493, 'intentions are the easiest to assess', 'намерения легче всего оценить'],
[494, 'what you mean?', 'что ты имеешь в виду?'],
[495, 'nice to meet you', 'рад встрече'],
[496, 'inner', 'внутренний'],
[497, 'considered in court', 'рассмотрено в суде'],
[498, 'you\'ll need to decide fast', 'вам придется решать быстро'],
[499, 'expect an event', 'ожидать событие'],
[500, 'visibility', 'видимость'],
[501, 'by publishing it privately', 'опубликовав его в частном порядке'],
[502, 'restrict access', 'ограничить доступ'],
[503, 'risk-free', 'без риска'],
[504, 'even though our love is doomed', 'даже если наша любовь обречена'],
[505, 'i\'m getting desperate', 'я в отчаянии'],
[506, 'desperate for a revolution', 'отчаянно нуждаюсь в серьезных переменах'],
[507, 'some kind of spark', 'какой-то искре'],
[508, 'some kind of connection', 'какой-то связи'],
[509, 'in these dangerous days', 'в эти опасные дни'],
[510, 'сome a little bit closer', 'подойди чуть ближе'],
[511, 'i need to understand', 'мне нужно понять'],
[512, 'why we kill the things we love the most', 'почему мы убиваем то, что любим больше всего'],
[513, 'kill the things we love', 'убиваем то, что мы любим'],
[514, 'but they don\'t burn like we do', 'но они не горят так, как мы'],
[515, 'burn', 'гореть'],
[516, 'no throttling', 'нет дросселирования'],
[517, 'obsolete', 'устаревший'],
[518, 'unnecessary', 'ненужный'],
[519, 'it seems the rain is starting', 'кажется дождь собирается'],
[520, 'adjust the height', 'регулировать высоту'],
[521, 'no spoon', 'ложки нет'],
[522, 'create and nest components', 'создавать и вкладывать компоненты'],
[523, 'contain capital letters', 'содержит заглавные буквы'],
[524, 'i imagine that right now you\'re feeling', 'я представляю, что прямо сейчас ты чувствуешь'],
[525, 'difficult, but not impossible', 'трудно, но не невозможно'],
[526, 'at last', 'наконец'],
[527, 'imagination', 'воображение'],
[528, 'a bit like Alice', 'немного похож на Алису'],
[529, 'tumbling down the rabbit hole', 'скатится в кроличью нору'],
[530, 'Alice in wonderland', 'Алиса в стране чудес'],
[531, 'you have the look', 'у тебя вид'],
[532, 'accept', 'принимать'],
[533, 'sees', 'видит'],
[534, 'becuase he\'s ecpecting to wake up', 'потому что он ожидает пробуждения'],
[535, 'i know exactly what you mean', 'я знаю точно, что ты имеешь в виду'],
[536, 'what you know, you can\'t explain', 'то что ты знаешь, ты не можешь объяснить'],
[537, 'but you feel it', 'но ты чувствуешь это'],
[538, 'you felt it your entire life', 'ты чувствовал это всю свою жизнь'],
[59, 'everywhere', 'везде'],
[540, 'in this very room', 'в этой самой комнате'],
[541, 'when you go to church', 'когда ты идешь в церковь'],
[542, 'when you pay your taxes', 'когда ты платишь свои налоги'],
[543, 'has been pulled over your eyes', 'был натянут на твои глаза'],
[544, 'to blind you from the truth', 'чтобы ослепить тебя от правды'],
[545, 'slave', 'раб'],
[546, 'everyone else', 'все остальные'],
[547, 'bondage', 'рабство'],
[548, 'prison', 'тюрьма'],
[549, 'smell', 'запах'],
[550, 'taste', 'вкус'],
[551, 'there is no turning back', 'нет пути назад'],
[552, 'believe whatever you want to believe', 'веришь во все, что ты хочешь верить'],
[553, 'stay', 'остаться'],
[554, 'you stay in wonderland', 'останешься в стране чудес'],
[555, 'how deep the rabbit hole goes', 'насколько глубока кроличья нора'],
[556, 'during the build', 'во время сборки'],
[557, 'props', 'реквизит'],
[558, 'command prompt', 'командная строка'],
[559, 'severity vulnerabilities', 'серьезность уязвимостей'],
[560, 'rendered', 'отображенный'],
[561, 'path', 'путь'],
[562, 'useState', 'использовать состояние'],
[563, 'initialState', 'начальное состояние'],
[564, 'attempt to assign', 'попытка назначить'],
[565, 'match', 'соответствовать'],
[566, 'mutable', 'изменяемый'],
[567, 'assignment', 'назначение'],
[568, 'instead', 'вместо'],
[569, 'saw', 'увидел'],
[570, 'restricted', 'ограниченный'],
[571, 'target', 'цель'],
[572, 'event', 'событие'],
[573, 'stopPropagation', 'остановить распространение'],
[574, 'bubbling', 'всплытие'],
[575, 'bind', 'связывать'],
[576, 'insertAdjacentElement', 'вставить соседний элемент'],
[577, 'beforebegin', 'перед началом'],
[578, 'toUpperCase', 'в верхний регистр'],
[579, 'closest', 'ближайший'],
[580, 'appendChild', 'добавить ребенка'],
[581, 'kattle', 'чайник'],
[582, 'your appearance now', 'твой внешний вид сейчас'],
[583, 'is what we call', 'это то, что мы называем'],
[584, 'residual self-image', 'остаточный само-образ'],
[585, 'is the mental projection', 'это ментальная проекция'],
[586, 'of your digital self', 'твоего цифрового себя'],
[587, 'if you\'re talking about', 'если ты говоришь о том'],
[588, 'what you can feel', 'что ты можешь чувствовать'],
[589, 'what you can smell', 'что ты можешь унюхать'],
[590, 'what you can taste and see', 'что ты можешь попробовать и увидеть'],
[591, 'then \"real\" is simply electrical signals', 'тогда реальность это просто электрические сигналы'],
[592, 'interpreted by your brain', 'интерпретированные твоим мозгом'],
[593, 'comprehensive', 'всесторонний'],
[594, 'excellent', 'отличный'],
[595, 'widely regarded as a hastily written', 'широко считается как поспешно написанный'],
[596, 'arbitrary file I/O', 'ввод/вывод произвольного файла'],
[597, 'the bare minimum', 'голый минимум'],
[598, 'describe', 'описывать'],
[699, 'this section is intended', 'этот раздел предназначен'],
[600, 'possible', 'возможный'],
[601, 'filling in a lot of the gaps', 'заполнение многих пробелов'],
[602, 'to some extent', 'в некоторой степени'],
[603, 'assigning', 'назначение'],
[604, 'avoid', 'избегать'],
[605, 'if not otherwise specified', 'если не указано другое'],
[606, 'make', 'делать'],
[607, 'where did it come from?', 'откуда это взялось?'],
[608, 'came', 'пришел'],
[609, 'where', 'где'],
[610, 'eventually', 'в конце концов'],
[611, 'does not look', 'не выглядит'],
[612, 'unaffected', 'незатронутый'],
[613, 'blueprint', 'план'],
[614, 'recipe', 'рецепт'],
[615, 'addition', 'дополнение'],
[616, 'advantage over', 'преимущество перед'],
[617, 'reminder', 'напоминание'],
[618, 'belonging', 'принадлежащий'],
[619, 'refers', 'относится'],
[620, 'the same holds', 'то же самое справедливо и для'],
[621, 'whithin', 'внутри'],
[622, 'attempt', 'попытка'],
[623, 'will invoke that setter', 'вызовет этот установщик'],
[624, 'something similar happens with classes', 'нечто подобное происходит и с классами'],
[625, 'native', 'родной'],
[626, 'native code', 'собственный код'],
[627, 'comprehension', 'понимание'],
[628, 'both', 'оба'],
[629, 'additional', 'дополнительный'],
[630, 'limitations', 'ограничения'],
[631, 'satisfactory', 'удовлетворительный'],
[632, 'introductory', 'вступительный'],
[633, 'after a few introductory sections', 'после нескольких вводных разделов'],
[634, 'remainder', 'остаток'],
[635, 'essential HTML', 'необходимый HTML'],
[636, 'brake', 'тормоз'],
[637, 'break', 'разрыв'],
[638, 'no end tag is needed', 'закрывающий тег не требуется'],
[639, 'feedback', 'обратная связь'],
[640, 'we promise', 'мы обещаем'],
[641, 'since you started evaluating,', 'с тех пор, как вы начали оценивать'],
[642, 'opinion', 'мнение'],
[643, 'purchasing', 'покупка'],
[644, 'foreword', 'предисловие'],
[645, 'complicated tooling', 'сложный инструмент'],
[646, 'explained', 'объясненный'],
[647, ' exercises', 'упражнения'],
[648, 'dive', 'нырять'],
[649, 'essentially', 'по существу'],
[650, 'own', 'собственный'],
[651, 'from scratch', 'с нуля'],
[652, 'advanced interactions', 'расширенные взаимодействия'],
[653, 'implementing real\r\nfeatures', 'реализация реальных функций'],
[654, 'management', 'управление'],
[655, 'the same as', 'то же самое, что'],
[656, 'interacts', 'взаимодействовать'],
[657, 'become increasingly popular', 'становятся все более популярными'],
[658, 'advanced beyond', 'продвинутый по сравнению'],
[659, 'yet another solution', 'еще одно решение'],
[660, 'every additional page', 'каждая дополнительная страница'],
[661, 'essentially everything crucial', 'по сути, все самое важное'],
[662, 'done by the server', 'выполняется сервером'],
[663, 'barebones', 'скудный'],
[664, 'curious', 'любопытный'],
[665, 'rather complex', 'довольно сложный'],
[666, 'keep on', 'продолжайте'],
[667, ' breakdown  folders and files', 'разбивка файлов и папок'],
[668, 'third-party dependencies', 'сторонние зависимости'],
[669, 'meet', 'встречайте'],
[670, 'similar to the example', 'аналогично приведенному примеру'],
[671, 'unless otherwise specified', 'если не указано другое'],
[672, 'will grow in size', 'будет увеличиваться в размерах'],
[673, 'pray', 'молиться'],
[674, 'lie around', 'лежать без дела'],
[675, 'void', 'пустой'],
[676, 'large amounts of JavaScript', 'большое количество JavaScript'],
[677, 'observer', 'наблюдатель'],
[678, 'subscribe', 'подписаться'],
[679, 'store', 'магазин'],
[680, 'equals', 'равно'],
[681, 'merge incoming changes', 'объединить входящие изменения'],
[682, 'fork', 'вилка'],
[683, 'defender', 'защитник'],
[684, 'scope', 'объем'],
[685, 'detached', 'отстраненный'],
[686, 'shit happens', 'дерьмо случается'],
[687, 'unsafe', 'небезопасный'],
[688, 'measuring performance', 'измерение производительности'],
[689, 'education', 'образование'],
[690, 'dispatch', 'отправлять'],
[691, 'action', 'действие'],
[692, 'lieutenant, you were given specific orders', 'лейтенант, вам были даны конкретные приказы'],
[693, 'crap', 'дерьмо'],
[694, 'the orders were for your protection', 'приказы были для твоей защиты'],
[695, 'i sent two units', 'я отправил две единицы'],
[696, 'they\'re bringing her down now', 'они доставляют ее сюда сейчас'],
[697, 'the line was traced', 'линия была прослежена'],
[698, 'they cut the hard line', 'они перерезали жесткую линию'],
[699, 'theres no time','нет времени'],
[700, 'you\'re gonna have to get another exit','тебе придется найти другой выход'],
[701, 'are there any agents?','есть какие-нибудь агенты?'],
[702, 'goddamn it','черт возьми'],
[703, 'you have to focus','ты должен сосредоточиться'],
[704, 'you can make it','ты можешь сделать это'],
[705, 'drop','уронить'],
[706, 'come take out the garbage', 'выкини мусор'],
[707, 'you are missing it', 'ты пропускаешь это'],
[708, 'get down here', 'давай сюда'],
[709, 'mismatched property value ', 'несоответствующее значение свойства'],
[710, 'safely', 'безопасно'],
[711, 'shorthand', 'сокращение'],
[712, 'assert','утверждать'],
[713, 'splice','сращивание'],
[714, 'score','рейтинг'],
[715, 'meets','встречается'],
[716, 'polygon','многоугольник'],
[717, 'rectangle','прямоугольник'],
[718, 'square','квадрат'],
[719, 'join','соединять'],
[720, 'sheep','овца'],
[721, 'increased','увеличенный'],
[722, 'bear in mind','имейте в виду'],
[723, 'hurt','болеть'],
[724, 'honestly','честно'],
[725, 'honestly','честно'],
[726, 'sake of simplicity','для простоты'],
[727, 'reduce','уменьшать'],
[728, 'slice','кусочек'],
[729, 'replace','заменять'],
[730, 'swapped','поменяли местами'],
[731, 'hence the name','отсюда и название'],
[732, 'otherwise','в противном случае'],
[733, 'behaviour described above','поведение описано выше'],
[734, 'consecutive','последовательный'],
[735, 'expanded','расширенный'],
[736, 'boring','скучный'],
[737, 'deoxyribonucleic acid (DNA)','дезоксирибонуклеиновая кислота (днк)'],
[738, 'foe','враг'],
[739, 'sequence','последовательность'],
[740, 'laid','проложенный'],
[741, 'arrived','приехал'],
[742, 'appointment','встреча'],
[743, 'short walk','короткая прогулка'],
[744, 'citizens','граждане'],
[745, 'traverse','пересекать'],
[746, 'south','юг'],
[747, 'greeting','приветствие'],
[748, 'exclamation mark','восклицательный знак'],
[749, 'assume','предполагать'],
[750, 'produce','производить'],
[751, 'rearranging','перестановка'],
[752, 'dice','игральная кость'],
[753, 'appropriate','соответствующий'],
[754, 'properly','правильно'],
[755, 'pass','проходить'],
[756, 'vowel','гласные'],
[757, 'sentence','предложение'],
[758, 'clever','умный'],
[759, 'recognition','распознавание'],
[760, 'fulfills','выполняет'],
[761, 'introduce','представлять'],
[762, 'partially','частично'],
[763, 'health','здоровье'],
[764, 'damage','повреждать'],
[765, 'combat','бой'],
[766, 'that system is our enemy','эта система - наш враг'],
[767, 'sentient','разумный'],
[768, 'survive','выживать'],
[769, 'guard','сторожить'],
[770, 'someone','кто-то'],
[771, 'succeed','преуспевать'],
[772, 'defer','отложить'],
[773, 'odd-length','нечетная длина'],
[774, 'awesome','потрясающий'],
[775, 'edit','редактировать'],
[776, 'determine','определять'],
[777, 'number is even','число четное'],
[778, 'order of the sequence','порядок последовательности'],
[779, 'tear','рвать'],
[780, 'petal','лепесток'],
[781, 'passionately', 'страстно'],
[782, 'survey','опрос'],
[783, 'not at all','нисколько'],
[784, 'torn','разорванный'],
[785, 'crie','плакать'],
[786, 'vacation','отпуск'],
[787, 'garden','сад'],
[788, 'plants','растения'],
[789, 'taken into consideration','принимая во внимание'],
[790, 'forecast','прогноз'],
[791, 'jealous neighbour','ревнивый сосед'],
[792, 'there are 2 gallons left','осталось 2 галлона'],
[793, 'considering these factors','учитывая эти факторы'],
[794, 'pump','насос'],
[795, 'sentence','предложение'],
[796, 'at least','по меньшей мере'],
[797, 'font facia','шрифтовая панель'],
[798, 'parse','разбор'],
[799, 'depth','глубина'],
[800, 'surface','поверхность'],
[801, 'area','область'],
[802, 'volume','объем'],
[803, 'split','разделять'],
[804, 'mangoes','манго'],
[805, 'quantity','количество'],
[806, 'useful','полезный'],
[807, 'refer','ссылаться'],
[808, 'recognition','распознавание'],
[809, 'prime numbers','простые числа'],
[810, 'ascending','восходящий'],
[811, 'bend','сгибать'],
[812, 'went past as','прошла мимо нас'],
[813, 'glitch','сбой'],
[814, 'to track it','отследить это'],
[815, 'choice','выбор'],
[816, 'we have to','мы должны'],
[817, 'north','север'],
[818, 'east','восток'],
[819, 'divisor','делитель'],
[820, 'subtrhuction','вычитание'],
[821, 'obtained','полученный'],
[822, 'several','несколько'],
[823, 'divided','разделенный'],
[824, 'unbelievable','невероятно'],
[825, 'happened','случилось'],
[826, 'prophecy','пророчество'],
[827, 'enough','достаточно'],
[828, 'term','термин'],
[829, 'odd','странный'],
[830, 'due to superstition','из-за суеверия'],
[831, 'given','данный'],
[832, 'calm','спокойствие'],
[833, 'sleigh', 'сани'],
[834, 'customers', 'клиенты'],
[835, 'tills','кассы'],
[836, 'hungry', 'голодный'],
[837, 'grab', 'схватить'],
[838, 'grasp', 'понять'],
]


scope.textContent = "слов в базе " + words.length;

let rand = 0;
let rightnum = 0;
let wrongnum = 0; 

function NewWord() {
rand = Math.round((words.length-1)*Math.random());
engword.textContent = words[rand][1];
rusword.value = '';
}

NewWord();

function Check() {
  switch(rusword.value.toLowerCase()){
    case(words[rand][2].toLowerCase()): 
                  rightnum += 1; right.textContent = rightnum;
                  rusword.style.borderColor = 'green'; NewWord();
                  percent.textContent = "процент правильных ответов " + Math.round(rightnum*100/(rightnum + wrongnum)) + "%"; break;
    case(''): rusword.value = "введите слово"; break;
    default: 
             rusword.value = "неправильно, " + words[rand][2]; 
             wrongnum +=1; wrong.textContent = wrongnum;
             rusword.style.borderColor = 'red';
	           percent.textContent = "процент правильных ответов " + Math.round(rightnum*100/(rightnum + wrongnum)) + "%"; break;
  }
}
 
document.addEventListener( 'keyup', event => {
  if( event.code === 'Enter') Check()
})
document.querySelector('#check').addEventListener('click', Check)

function test() {
  return words.find(el => {
    if (el[1] === 'customers') console.log(el[0])
  })
}
test()



